// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function CancelDownload(arg1:string):Promise<model.Result>;

export function DeleteCachedLayer(arg1:string):Promise<model.Result>;

export function DeleteJob(arg1:string):Promise<model.Result>;

export function ExportConfig():Promise<model.Result>;

export function ClearLayerCache():Promise<model.Result>;

export function GetBuildInfo():Promise<Record<string, string>>;

export function GetDefaultOutputDir():Promise<string>;

export function GetDownload(arg1:string):Promise<model.DownloadTask>;

export function GetLayerCache():Promise<model.LayerCacheInfo>;

export function GetLayerCacheInventory():Promise<model.LayerCacheInventory>;

export function GetVersion():Promise<string>;

export function ImportConfig():Promise<model.Result>;

export function ListJobs():Promise<Array<model.Job>>;

export function ListPlatforms():Promise<Array<model.Platform>>;

export function LoadConfig():Promise<model.FileConfig>;

export function OpenLayerCacheDir():Promise<model.Result>;

export function OpenOutputDir(arg1:string):Promise<model.Result>;

export function ParseImage(arg1:string,arg2:string,arg3:boolean):Promise<model.ImageReference>;

export function PruneLayerCache():Promise<model.Result>;

export function SaveConfig(arg1:model.FileConfig):Promise<model.Result>;

export function SaveJob(arg1:model.Job):Promise<model.Job>;

export function SelectOutputDir():Promise<string>;

export function StartDownload(arg1:model.DownloadRequest):Promise<string>;

export function StartJob(arg1:string):Promise<string>;

export function TestRegistry(arg1:model.RegistryConfig):Promise<model.TestRegistryResult>;
