// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelDownload(arg1) {
  return window['go']['app']['App']['CancelDownload'](arg1);
}

export function DeleteCachedLayer(arg1) {
  return window['go']['app']['App']['DeleteCachedLayer'](arg1);
}

export function DeleteJob(arg1) {
  return window['go']['app']['App']['DeleteJob'](arg1);
}

export function ExportConfig() {
  return window['go']['app']['App']['ExportConfig']();
}

export function ClearLayerCache() {
  return window['go']['app']['App']['ClearLayerCache']();
}

export function GetBuildInfo() {
  return window['go']['app']['App']['GetBuildInfo']();
}

export function GetDefaultOutputDir() {
  return window['go']['app']['App']['GetDefaultOutputDir']();
}

export function GetDownload(arg1) {
  return window['go']['app']['App']['GetDownload'](arg1);
}

export function GetLayerCache() {
  return window['go']['app']['App']['GetLayerCache']();
}

export function GetLayerCacheInventory() {
  return window['go']['app']['App']['GetLayerCacheInventory']();
}

export function GetVersion() {
  return window['go']['app']['App']['GetVersion']();
}

export function ImportConfig() {
  return window['go']['app']['App']['ImportConfig']();
}

export function ListJobs() {
  return window['go']['app']['App']['ListJobs']();
}

export function ListPlatforms() {
  return window['go']['app']['App']['ListPlatforms']();
}

export function LoadConfig() {
  return window['go']['app']['App']['LoadConfig']();
}

export function OpenLayerCacheDir() {
  return window['go']['app']['App']['OpenLayerCacheDir']();
}

export function OpenOutputDir(arg1) {
  return window['go']['app']['App']['OpenOutputDir'](arg1);
}

export function ParseImage(arg1, arg2, arg3) {
  return window['go']['app']['App']['ParseImage'](arg1, arg2, arg3);
}

export function PruneLayerCache() {
  return window['go']['app']['App']['PruneLayerCache']();
}

export function SaveConfig(arg1) {
  return window['go']['app']['App']['SaveConfig'](arg1);
}

export function SaveJob(arg1) {
  return window['go']['app']['App']['SaveJob'](arg1);
}

export function SelectOutputDir() {
  return window['go']['app']['App']['SelectOutputDir']();
}

export function StartDownload(arg1) {
  return window['go']['app']['App']['StartDownload'](arg1);
}

export function StartJob(arg1) {
  return window['go']['app']['App']['StartJob'](arg1);
}

export function TestRegistry(arg1) {
  return window['go']['app']['App']['TestRegistry'](arg1);
}
